# Generated by Django 5.2.5 on 2025-08-09 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='schedule',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_times',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clinic'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
    ]
